### ISSUE TITLE
Problem comparing enum values

### ISSUE THREAD

**Issue by VaughanJackson** [eXparity/hamcrest-bean#7]
- I have come across what looks like incorrect behaviour to me. I was using a library class which ultimately uses hamcrest-bean's `TheSameAs.comparesSafely()` to compare two object graphs as part of unit testing.
- A unit test seemed to be passing inappropriately, because one attribute value in the two object graphs being compared differed, but was found to be the same by `TheSameAs.compareObjects()`:
- The attribute in question was a Java `enum`, and in one object graph had, for example, `VALUE_A`, whilst in the other it had the value `VALUE_B`. The types did not differ, just the values. However, `TheSameAs.compareObjects()` did not find the values to differ, and so `TheSameAs.addMismatch()` is not called.
- Perhaps `TheSameAs.compareObjects()` should be modified to provide special comparison behaviour for `enum` values?

**Comment by stewbis** [comment]
Hi Vaughan, first up apologies for not getting on this straight away, and yep I can confirm the problem as well with a test case I setup. I've merge in your pull request and will create a new release to push up to maven central. Regards, Stewart

**Comment by VaughanJackson** [comment]
Hi Stewart,No problem. Glad to have been of service.Regards,Vaughan.

Sent from Yahoo Mail on Android 
 
  On Wed, 21 Mar 2018 at 13:25, Stewart Bissett<notifications@github.com> wrote:   
Hi Vaughan, first up apologies for not getting on this straight away, and yep I can confirm the problem as well with a test case I setup. I've merge in your pull request and will create a new release to push up to maven central. Regards, Stewart

**Comment by cpcundill** [comment]
Great stuff @VaughanJackson.  @stewbis Any idea when there will be another release with @VaughanJackson's fix ?

**Comment by stewbis** [comment]
Hi @cpcundill, I'll cut one today with @VaughanJackson fix in it.

**Comment by stewbis** [comment]
New release version cut and pushed to maven central, should be there with an hour or so (although they warn it can take 24 hours). Include 1.0.12 in your pom, gradle, etc and you'll pick up the fix.
